In [ ]:
!python --version

Python 3.10.12


# Модуль 1

In [ ]:
print('Hello, world!')

Hello, world!


In [ ]:
#print('Hello, world!')

In [ ]:
print('Hello, world!')
print('Hello', 'world!')
print('Hello'+'world!')

Hello, world!
Hello world!
Helloworld!


In [ ]:
# запрашиваем у пользователя имя и приветствуем его
name = input('Введите Ваше имя:')
print('Привет '+ name + '!')

Введите Ваше имя:Эдуард
Привет Эдуард!


In [ ]:
# запрашиваем у клиента возраст и рассчитываем год его рожденния
age = input('введите Ваш возраст:')
year_of_birth = 2023 - int(age)
print('Вы родились в ' + str(year_of_birth) + ' году')

введите Ваш возраст:51
Вы родились в 1972 году


In [ ]:
# рассчитываем возраст пользователя в днях и выводим результат
age = input('введите Ваш возраст:')
age_in_days = int(age) * 365
print('Ваш возраст в днях составляет: ' + str(age_in_days))

введите Ваш возраст:51
Ваш возраст в днях составляет: 18615


Google Colab — удобный инструмент для анализа данных ❤

In [ ]:
print ((31 % 2) + (-31 % 2))

2


In [ ]:
print (13 % -3 * 3 - 3**2)

-15


In [ ]:
print(round(11*2.5/3, 2))

9.17


In [ ]:
print(round(3.14159**2/2))

5


In [ ]:
1.57*3/1.5

3.14

In [ ]:
3**3-3*(6*3-4.5*2)

0.0

In [ ]:
a = 25
b = 25
a = 15
print(b)

25


In [ ]:
days, hour, min, sec = int(input()), int(input()), int(input()), int(input())
print('Общее количество секунд: ', sec + min * 60 + hour * 3600 + days * 3600 * 24)

1
2
3
4
Общее количество секунд:  93784


Поиск наиболее часто встречающегося слова в предложении:
Напишите программу, которая запрашивает у пользователя предложение и определяет наиболее часто встречающееся слово в этом предложении. Выведите это слово на экран. В данной задаче можно предположить, что предложение состоит только из слов, разделенных пробелами.

In [ ]:
sentence = input()
list_words = sentence.split()
print(max(list_words, key=list_words.count))

z kfkf kfkf wee
kfkf


# Модуль 2.1

In [ ]:
a = [-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]
a_slice = a[4:9]
print(a_slice)

[-1, 0, 1, 2, 3]


In [ ]:
a = [-3, -2, -1, 0, 1, 2, 3, 4, 5, 6]
a_slice = a[::-1]
print(a_slice)

[6, 5, 4, 3, 2, 1, 0, -1, -2, -3]


In [ ]:
s = 'hello kitty'
list_s = s.split()

print(list_s[-2:])

['hello', 'kitty']


In [ ]:
a = 'order1'
b = 'order2'
c = 'order3'
orders = []
orders.append(a)
orders.append(b)
orders.append(c)
print(orders)

['order1', 'order2', 'order3']


In [ ]:
book1 = 'my book'
book2 = 'your book'
books = ['all_books']
books.append(book1)
books.append(book2)
print(books)

['all books', 'my book', 'your book']


In [ ]:
letters = ['a', 'b', 'c', 'd', 'e']
print(letters)
letters.clear()
print(letters)

['a', 'b', 'c', 'd', 'e']
[]


In [ ]:
numbers = [5, 5, 7, 5, 2, 3, 1, 1, 2, 4]
print(numbers.count(5))
print(numbers.count(1))

3
2


In [ ]:
my_books = ['book1', 'book2', 'book3', 'book4', 'book5']
tom_books = my_books[:]
print(my_books, tom_books, sep='\n')

['book1', 'book2', 'book3', 'book4', 'book5']
['book1', 'book2', 'book3', 'book4', 'book5']


In [ ]:
my_orders = ['order1', 'order2', 'order3', 'order4', 'order5']
anne_orders = my_orders.copy()
print(my_orders, anne_orders, sep='\n')

['order1', 'order2', 'order3', 'order4', 'order5']
['order1', 'order2', 'order3', 'order4', 'order5']


In [ ]:
all_things = ['order1', 'order2', 'order3']
only_books = ['book1', 'book2']
all_things.extend(only_books)
print(all_things)

['order1', 'order2', 'order3', 'book1', 'book2']


In [ ]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
nums.reverse()
print(nums)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
random_values = [3, 5, 0, -1, 2, 10, 15, -5]
random_values.sort()
print(random_values)

[-5, -1, 0, 2, 3, 5, 10, 15]


In [ ]:
list1 = [5, 0.2, 'hello there', [1,2,3,4], 'bye']
print(list1)

[5, 0.2, 'hello there', [1, 2, 3, 4], 'bye']


In [ ]:
tpl = tuple()
print(tpl)

()


In [ ]:
tpl2 = 255,
print(tpl2)

(255,)


In [ ]:
tpl3 = (15,22,0)
print(tpl3)

(15, 22, 0)


In [ ]:
empty_dict1 = dict()
empty_dict2 = {}
print(empty_dict1, empty_dict2)

{} {}


In [ ]:
alphabet_dict = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
print(alphabet_dict['d'])

4


In [ ]:
place_and_money = {1:100, 2:50, 3:10}
print(place_and_money[2])

50


In [ ]:
place_and_money = {1: 100, 2: 50, 3: 10}
place_and_money[4] = 5
print(place_and_money)

{1: 100, 2: 50, 3: 10, 4: 5}


In [ ]:
place_and_money = {1: 100, 2: 50, 3: 10}
place_and_money[3] = 25
print(place_and_money)

{1: 100, 2: 50, 3: 25}


In [ ]:
place_and_money = {1: 100, 2: 50, 3: 10}
place_and_money.clear()
print(place_and_money)

{}


In [ ]:
place_and_money = {1: 100, 2: 50, 3: 10}
print(place_and_money.keys())

dict_keys([1, 2, 3])


In [ ]:
name_to_age = {'Anne': 22, 'Anton': 27, 'Phillip': 30}
print(name_to_age.keys())

dict_keys(['Anne', 'Anton', 'Phillip'])


In [ ]:
name_to_age = {'Anne': 22, 'Anton': 27, 'Phillip': 30}
print(name_to_age.values())

dict_values([22, 27, 30])


In [ ]:
place_and_money = {1: 100, 2: 50, 3: 10}
print(place_and_money.values())

dict_values([100, 50, 10])


In [ ]:
place_and_money = {1: 100, 2: 50, 3: 10}
print(place_and_money.get(20, 0))

0


In [ ]:
name_to_age = {'Anne': 22, 'Anton': 27, 'Phillip': 30}
print(name_to_age.get('Danny', -1))

-1


In [ ]:
place_and_money = {1: 100, 2: 50, 3: 10}
place_and_money.update({4:5, 5:1})
print(place_and_money)

{1: 100, 2: 50, 3: 10, 4: 5, 5: 1}


In [ ]:
name_to_age = {'Anne': 22, 'Anton': 27, 'Phillip': 30}
name_to_age.update({'Anne':23, 'Phillip':29})
print(name_to_age)

{'Anne': 23, 'Anton': 27, 'Phillip': 29}


In [ ]:
place_and_money = {1: 100, 2: 50, 3: 10}
result = place_and_money.pop(3)
print(result)

10


In [ ]:
name_to_age = {'Anne': 22, 'Anton': 27, 'Phillip': 30}
result = name_to_age.pop('Anton')
print(result)

27


In [ ]:
place_and_money = {1: 100, 2: 50, 3: 10}
place_and_money.setdefault(10, 1)
print(place_and_money)

{1: 100, 2: 50, 3: 10, 10: 1}


In [ ]:
name_to_age = {'Anne': 22, 'Anton': 27, 'Phillip': 30}
name_to_age.setdefault('Anne', 32)
print(name_to_age)

{'Anne': 22, 'Anton': 27, 'Phillip': 30}


In [ ]:
test_dict = {}
test_dict[5] = [3,4,5]
test_dict[(3,4,5)] = 'strong man'
print(test_dict)

{5: [3, 4, 5], (3, 4, 5): 'strong man'}


In [ ]:
test_dict2 = {'name':'Sancho', 'surname': 'Panso', 'info': {'age': 35, 'country': 'Mexico'}}
print(test_dict2)

{'name': 'Sancho', 'surname': 'Panso', 'info': {'age': 35, 'country': 'Mexico'}}


In [ ]:
test_dict3 = {'info': [10, 15, 27], 'about': {'game': 'football', 'period': 5}}
test_dict3['about'] = 'dont know'
print(test_dict3)

{'info': [10, 15, 27], 'about': 'dont know'}


In [ ]:
s1 = set()
print(s1)

set()


In [ ]:
s2 = {5, 10, 3, 2, 11}
print(s2)

{2, 3, 5, 10, 11}


In [ ]:
s3 = set('wow thats cool')
print(s3)

{'o', 's', 'a', ' ', 'c', 'w', 'h', 'l', 't'}


In [ ]:
s1 = {'a', 'b', 'c', 'd', 'e'}
s1.add('hello')
print(s1)

{'e', 'd', 'a', 'c', 'hello', 'b'}


In [ ]:
s1 = {'a', 'b', 'c', 'd', 'e'}
s1.remove('d')
print(s1)

{'e', 'a', 'c', 'b'}


In [ ]:
s1 = {'a', 'b', 'c', 'd', 'e', 'f'}
s1.discard('f')
print(s1)

{'e', 'd', 'a', 'c', 'b'}


In [ ]:
s1 = {'a', 'b', 'c', 'd', 'e', 'f'}
s1.remove('f')
print(s1)

{'e', 'd', 'a', 'c', 'b'}


In [ ]:
alpha_set = {'a', 'b', 'c', 'd', 'e'}
name = set('bad boy')
alpha_set = alpha_set.union(name)
print(alpha_set)

{'o', 'e', 'd', 'a', ' ', 'y', 'b', 'c'}


In [ ]:
num_set = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
date_num = {1, 9, 4, 8}
num_set = num_set.union(date_num)
print(num_set)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


In [ ]:
alpha_set = {'a', 'b', 'c', 'd', 'e'}
name = set('bad boy')
alpha_set = alpha_set.intersection(name)
print(alpha_set)

{'d', 'a', 'b'}


In [ ]:
num_set = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
date_num = {1, 9, 4, 8}
num_set = num_set.intersection(date_num)
print(num_set)

{8, 1, 4, 9}


In [ ]:
alpha_set = {'a', 'b', 'c', 'd', 'e'}
name = set('bad boy')
alpha_set = alpha_set.difference(name)
print(alpha_set)

{'e', 'c'}


In [ ]:
num_set = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
date_num = {1, 9, 4, 8}
num_set = num_set.difference(date_num)
print(num_set)

{0, 2, 3, 5, 6, 7, 10}


In [ ]:
cluster1 = {"item1", "item2", "item3"}
cluster2 = {"item2", "item3", "item4", "item5", "item6"}
cluster1.issubset(cluster2)

False

In [ ]:
int_one = 1
str_one = str(int_one)
print(str_one)

1


In [ ]:
str_age_begin = 'my age is '
int_age = 18
result_string = str_age_begin + str(int_age)
print(result_string)

my age is 18


In [ ]:
str_brothers_begin = 'I have '
count = 5
str_brothers_end = ' brothers'
result_sentence = str_brothers_begin + str(count) + str_brothers_end
print(result_sentence)

I have 5 brothers


In [ ]:
list2 = list(range(-5, 15, 2))
list3 = [1,2,3,4]
list3.extend(list2)
print(list3)

[1, 2, 3, 4, -5, -3, -1, 1, 3, 5, 7, 9, 11, 13]


In [ ]:
list6 = [3, 1, -10, 5, 11, 20, 1, -10]
list7 = list6[:]
list6.sort()
list_result = list6[::-1]
print(list7, list_result, sep='\n')

[3, 1, -10, 5, 11, 20, 1, -10]
[20, 11, 5, 3, 1, 1, -10, -10]


In [ ]:
list1 = [10, 15]
tpl = tuple(list1)
dict1 = {tpl:'hello'}
print(dict1)

{(10, 15): 'hello'}


In [ ]:
dict1 = {'name': 'unknown'}
dict2 = {'name': 'Tom'}
print(dict1, dict2, dict1.keys(), dict1.values(), sep='\n')

{'name': 'unknown'}
{'name': 'Tom'}
dict_keys(['name'])
dict_values(['unknown'])


In [ ]:
s1 = set('hello')
s2 = set(['w', 'o', 'w'])
print(s1.union(s2), s1.intersection(s2), s1.difference(s2), sep='\n')

{'o', 'e', 'w', 'h', 'l'}
{'o'}
{'e', 'h', 'l'}


# Модуль 2.2

In [ ]:
not True or (True and not True)

False

In [ ]:
not False and True or False and not True

True

In [ ]:
x = 10
y = 100
z = (x % 2 == 0) and (y >= 100)
v = (x % 2 == 0) or (y >= 100)
w = not(x % 2 == 0) or not(y >= 100)
print(z, v, w)

True True False


In [ ]:
dish, street = 'Рамен с говядиной', 'Заводской'
## Заказ будет доставлен вовремя

dish_time_dict = {
    'Рамен с говядиной': 15,
    'Суши': 18,
    'Лагман с курицей': 20,
    'Лагман с говядиной': 24,
    'Плов с курицей': 28
}

street_time_dict  = {
    'Дзержинский': 39,
    'Солнечный': 40,
    'Заводской': 27,
    'Гагаринский': 43,
    'Кировский': 37,
    'Октябрьский': 34
}

if street not in street_time_dict:
    # неизвестный район
    print("Доставка в ваш район недоступна")
elif dish not in dish_time_dict:
    # неизвестное блюдо
    print("Блюдо недоступно, закажите что-то другое")
else:
    # район доступен для доставки и блюдо известно
    dish_time = dish_time_dict[dish] # время приготовления блюда
    street_time = street_time_dict[street] # время доставки
    full_time = dish_time + street_time  # общее время доставки
    delay = full_time - 60  # задержка
    if delay <= 0:
        # задержка не положительна
        print("Заказ будет доставлен вовремя")
    else:
        # задержка положительная
        print("Курьер задержится на {} минут".format(delay))

Заказ будет доставлен вовремя


In [ ]:
errors_dict = {
    'length': 'Длина пароля не равна 8 символам',
    'digits': 'Пароль состоит только из цифр',
    'letters': 'Пароль состоит только из букв',
    'upper': 'Отсутствуют заглавные буквы',
    'lower': 'Отсутствуют строчные буквы',
    'spec': 'Отсутствуют спецсимволы в пароле',
    'bad_symbols': 'В пароле использованы непредусмотренные символы'
}

bad_symbols = ['!', '@', '$', '%', '^', '`', '&', '(', ')', '+', '=', '_', '~']

password = 'Aafaf*al'

# Проверяем длину пароля
if len(password) == 8:
    errors_dict.pop('length')

# Проверяем, что пароль НЕ состоит только из цифр
if not password.isdigit():
    errors_dict.pop('digits')

# Проверяем, что пароль НЕ состоит только из букв
if not password.isalpha():
    errors_dict.pop('letters')

# Проверяем, есть ли в пароле заглавные буквы
if password.lower() != password:
    errors_dict.pop('upper')

# Проверяем, есть ли в пароле строчные буквы
if password.upper() != password:
    errors_dict.pop('lower')

# Проверяем, есть ли в пароле специальные символы
if '*' in password or '-' in password or '#' in password:
    errors_dict.pop('spec')
    # Проверяем, встречаются ли спец символы в пароле несколько раз
    if password.count('*') > 1 or password.count('-') > 1 or password.count('#') > 1:
        errors_dict['spec_count'] = 'Какой-то из спецсимволов в пароле использован более одного раза'

# Проверяем, есть ли в пароле запрещенные символы
if len(set(password).intersection(set(bad_symbols))) == 0:
    errors_dict.pop('bad_symbols')

# Проверяем результирующую длину чек-листа
if len(errors_dict) > 0:
    print(list(errors_dict.values()))
else:
    print('Пароль идеален!')

['Длина пароля не равна 8 символам']


# Модуль 3

In [ ]:
my_list = [1]
for i in range(10):
    my_list.append(my_list[i] * 2)
print(my_list)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]


In [ ]:
# Задаём число
n = 27
# Создаём бесконечный цикл
while True:
    # Проверяем условие, что остаток от деления на 3 равен 0.
    if n % 3 == 0:
        # Если условие выполняется, новое число — результат целочисленного деления на 3.
        n = n // 3
        # Проверяем условие, что в результате деления получили 1.
        if n == 1:
            # Выводим утвердительное сообщение
            print('n - is the power of the number 3!')
            # Выходим из цикла
            break
    else:
        # В противном случае выводим сообщение-опровержение
        print('n - is not the power of the number 3!')
        # Выходим из цикла
        break
## Будет выведено:
## n - is the power of the number 3!

n - is the power of the number 3!


In [ ]:
# Заданный словарь
client_status = {
    103303: 'yes',
    103044: 'no',
    100423: 'yes',
    103032: 'no',
    103902: 'no'
}
# Создаём цикл по ключам словаря client_status
for user_id in client_status: # user_id — текущий ключ словаря

    if client_status[user_id] == 'no':
        # Если текущий статус == 'no', переходим на следующую итерацию.
        continue
    else:
        # В противном случае переходим на следующую итерацию
        print('Send present user', user_id)

Send present user 103303
Send present user 100423


In [ ]:
text = """
The rabbit-hole went straight on like a tunnel for some way, and then dipped suddenly down, so suddenly that Alice had not a moment to think about stopping herself before she found herself falling down a very deep well.

Either the well was very deep, or she fell very slowly, for she had plenty of time as she went down to look about her and to wonder what was going to happen next. First, she tried to look down and make out what she was coming to, but it was too dark to see anything; then she looked at the sides of the well, and noticed that they were filled with cupboards and book-shelves; here and there she saw maps and pictures hung upon pegs. She took down a jar from one of the shelves as she passed; it was labelled `ORANGE MARMALADE', but to her great disappointment it was empty: she did not like to drop the jar for fear of killing somebody, so managed to put it into one of the cupboards as she fell past it.

`Well!' thought Alice to herself, `after such a fall as this, I shall think nothing of tumbling down stairs! How brave they'll all think me at home! Why, I wouldn't say anything about it, even if I fell off the top of the house!' (Which was very likely true.)
"""


# Приводим текст к нижнему регистру
text = text.lower()
# Заменяем пробелы на пустые строки
text = text.replace(" ", "")
# Заменяем символы переноса строки на пустые строки
text = text.replace("\n", "")
# Создаём пустой словарь для подсчёта количества символов
count_dict = {}
# Создаём цикл по символам в строке text
for symbol in text: # symbol — текущий символ в тексте
    # Проверяем условие, что символа ещё нет среди ключей словаря.
    if symbol not in count_dict:
        # Если условие выполняется, заносим символ в словарь со значением 1.
        count_dict[symbol] = 1 #
    else:
        # В противном случае увеличиваем частоту символа
        count_dict[symbol] += 1
# Выводим результирующий словарь
print(count_dict)
## {'t': 88, 'h': 63, 'e': 112, 'r': 39, 'a': 70, 'b': 15, 'i': 47, '-': 2, 'o': 80, 'l': 55, 'w': 31, 'n': 57, 's': 60, 'g': 17, 'k': 14, 'u': 22, 'f': 28, 'm': 17, 'y': 18, ',': 13, 'd': 43, 'p': 23, 'c': 9, 'v': 8, '.': 5, 'x': 1, ';': 3, 'j': 2, '`': 3, "'": 5, ':': 1, '!': 4, '(': 1, ')': 1}

{'t': 88, 'h': 63, 'e': 112, 'r': 39, 'a': 70, 'b': 15, 'i': 47, '-': 2, 'o': 80, 'l': 55, 'w': 31, 'n': 57, 's': 60, 'g': 17, 'k': 14, 'u': 22, 'f': 28, 'm': 17, 'y': 18, ',': 13, 'd': 43, 'p': 23, 'c': 9, 'v': 8, '.': 5, 'x': 1, ';': 3, 'j': 2, '`': 3, "'": 5, ':': 1, '!': 4, '(': 1, ')': 1}


In [ ]:
text = """
She sells sea shells on the sea shore;
The shells that she sells are sea shells I am sure.
So if she sells sea shells on the sea shore,
I am sure that the shells are sea shore shells.
"""
# Приводим текст к нижнему регистру
text = text.lower()
# Заменяем символы переноса строки на пробелы
text = text.replace("\n", " ")
# Заменяем запятые на пустые строки
text = text.replace(",", "")
# Заменяем точки на пустые строки
text = text.replace(".", "")
# Заменяем точки с запятыми на пустые строки
text = text.replace(";", "")
# Разделяем текст на слова
word_list = text.split()
# Создаём пустой словарь для подсчёта количества слов
count_dict = {}
# Создаём цикл по словам в списке word_list
# word — текущее слово из списка word_list
for word in word_list:
    # Проверяем условие, что слова ещё нет среди ключей словаря.
    if word not in count_dict:
        # Если условие выполняется, заносим слово в словарь со значением 1.
        count_dict[word] = 1
    else:
        # В противном случае увеличиваем частоту слова
        count_dict[word] += 1
# Выводим результирующий словарь
print(count_dict)


## Будет выведено:
## {'she': 3, 'sells': 3, 'sea': 6, 'shells': 6, 'on': 2, 'the': 4, 'shore': 3, 'that': 2, 'are': 2, 'i': 2, 'am': 2, 'sure': 2, 'so': 1, 'if': 1}

{'she': 3, 'sells': 3, 'sea': 6, 'shells': 6, 'on': 2, 'the': 4, 'shore': 3, 'that': 2, 'are': 2, 'i': 2, 'am': 2, 'sure': 2, 'so': 1, 'if': 1}


# Модуль 4.1

In [ ]:
def get_less(list_in, num):
    res = None

    if list_in is not None:
        for el in list_in:
            if el < num:
                res = el
                break

    return res

print(get_less([1, 5, 8, 10], 8))
print(get_less([1, 5, 8, 10], 0))
print(get_less([], 25))

1
None
None


In [ ]:
def split_date(date):
    res = []
    res.append(int(date[:2]))
    res.append(int(date[2:4]))
    res.append(int(date[-4:]))

    return tuple(res)

print(split_date("31012019"))
# (31, 1, 2019)

(31, 1, 2019)


In [ ]:
def is_prime(num):
    k = 0
    if num == 1:
        res = False
    elif num != 1:
        for i in range(2, num // 2+1):
            if (num % i == 0):
                k = k+1
        if (k <= 0):
            res = True
        else:
            res = False
    return res

print(is_prime(1))
print(is_prime(10))
print(is_prime(13))
# False
# False
# True

False
False
True


In [ ]:
def between_min_max(*args):
    res = (max(args) + min(args))/2
    return res

print(between_min_max(10))
print(between_min_max(1,2,3,4,5))
# 10.0
# 3.0

10.0
3.0


In [ ]:
def best_student(**kwargs):
    res = sorted(kwargs, key=kwargs.get)
    return res[0]

print(best_student(Tom=12, Mike=3))
print(best_student(Tom=12))
print(best_student(Tom=12, Jerry=1, Jane=2))
# Mike
# Tom
# Jerry

Mike
Tom
Jerry


In [ ]:
def is_palindrom(x):
    if (lambda x: x == x[::-1])(x.lower()):
        res = 'yes'
    else:
        res = 'no'
    return res

print(is_palindrom('1234'))
print(is_palindrom('12321'))
# no
# yes

no
yes


In [ ]:
area = lambda a,b: a*b

print(area(12,5))
# 60

60


In [ ]:
between_min_max = lambda *args: (max(args) + min(args)) / 2

print(between_min_max(1,2,3,4,5))
# 3.0

3.0


In [ ]:
def sort_ignore_case(ls):
    sorted_ls = sorted(ls, key=lambda s: s.casefold())
    return sorted_ls

print(sort_ignore_case(['Acc', 'abc']))
# ['abc', 'Acc']

['abc', 'Acc']


In [ ]:
def exchange(usd=None, rub=None, rate=None):
    if usd is not None and rub is not None and rate is not None:
        raise ValueError('Too many arguments')
    elif usd is None and rub is None or usd is None and rate is None or rub is None and rate is None:
        raise ValueError('Not enough arguments')
    res = 0
    if usd is not None and rub is not None:
        res = rub / usd
    elif usd is not None and rate is not None:
        res = usd * rate
    elif rub is not None and rate is not None:
        res = rub / rate

    return res

print(exchange(usd=100, rub=8500))
print(exchange(usd=100, rate=85))
print(exchange(rub=1000, rate=85))
# 85.0
# 8500
# 11.764705882352942
#print(exchange(rub=1000, rate=85, usd=90))
# ValueError: Too many arguments
#print(exchange(rub=1000))
# ValueError: Not enough arguments

85.0
8500
11.764705882352942


# Модуль 4.2

In [ ]:
# Внешняя функция для вычисления итоговой стоимости
def calculate_cost(cost, sale):
    # Внутренняя функция для предобработки аргумента sale
    def preprocessing_sale():
        # Объявляем, что используем нелокальную переменную sale
        nonlocal sale
        # Если sale — строка
        if type(sale) is str:
            # Удаляем из строки '%', приводим к float и делим на 100
            sale = float(sale.replace('%', '')) / 100
        # Если sale — целое число
        elif type(sale) is int:
            # Делим его на 100
            sale = sale / 100
        # Если используется некорректный формат
        elif type(sale) is not str or type(sale) is not int or type(sale) is not float:
            raise ValueError("Некорректный формат скидки")
    # Запускаем предобработку, прежде чем вычислить стоимость
    preprocessing_sale()
    # Считаем итоговую стоимость и возвращаем её
    # (стоимость — стоимость * скидка)
    return cost - cost * sale

print(calculate_cost(1330, '15%'))
print(calculate_cost(1330, 15))


1130.5
1130.5


In [ ]:
print(dir(__builtins__))

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EncodingWarning', 'EnvironmentError', 'Exception', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'StopIteration', 'SyntaxError', 'SyntaxWar

In [ ]:
# Внешняя функция для обработки списка из строк
def processing_list(answers):
    # Внутренняя функция для выполнения обработки одного элемента списка
    def preprocessing_answer(answer):
        # Приводим к нижнему регистру
        answer = answer.lower()
        # Удаляем стоп-символы
        stop_symbols = '"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~!'
        # Создаём цикл по символам в строке
        for sym in stop_symbols:
            # Если стоп-символ есть в строке answer
            if sym in answer:
                # Заменяем стоп-символы в строке на пустые строки
                answer = answer.replace(sym, '')
        return answer
    # Создаём пустой список, куда будем добавлять результаты
    result = []
    # Создаеё цикл по всем элементам списка
    for answer in answers:
         # Добавляем предобработанную строку в лог-список
        result.append(preprocessing_answer(answer))
    return result

print(processing_list(['Мама мыла раму, раму мыла мама', 'Hello & world!']))

['мама мыла раму раму мыла мама', 'hello  world']


In [ ]:

old_list = ['1', '2', '3', '4', '5', '6', '7']
new_list = list(map(int, old_list))
print(new_list)
## new_list = [1, 2, 3, 4, 5, 6, 7]
old_list = ['101', '203', '33', '45', '51', '46', '77']
new_list = list(map(int, old_list))
print(new_list)
## new_list = [101, 203, 33, 45, 51, 46, 77]

[1, 2, 3, 4, 5, 6, 7]
[101, 203, 33, 45, 51, 46, 77]


In [ ]:
expenses = [[2356, 4537, 8678], [7395, 1298, 6500, 4791],[6341, 3408], [1105, 8374, 5914], [1024, 7333], [3500, 2008, 9375, 6144]]

expenses_sum = list(map(sum, expenses))
print(expenses_sum)
## expenses_sum = [15571, 19984, 9749, 15393, 8357, 21027]


[15571, 19984, 9749, 15393, 8357, 21027]


In [ ]:
prices = {'яблоко': 99, 'апельсин': 99, 'вишня': 147, 'персик': 145, 'грейпфрут': 139}

def discount_func(price_tuple, discount=5):
    name, price = price_tuple
    new_price = round(price - (price * discount/100), 2)
    return (name,new_price)
new_prices = dict(map(discount_func, list(prices.items())))
print(new_prices)
## new_prices = {'яблоко': 94.05, 'апельсин': 94.05, 'вишня': 139.65, 'персик': 137.75, 'грейпфрут': 132.05}

{'яблоко': 94.05, 'апельсин': 94.05, 'вишня': 139.65, 'персик': 137.75, 'грейпфрут': 132.05}


In [ ]:
docs = [
'//doc/5041434?query=data%20science',
'//doc/5041567?query=data%20science',
'//doc/4283670?query=data%20science',
'//doc/3712659?query=data%20science',
'//doc/4997267?query=data%20science',
'//doc/4372673?query=data%20science',
'//doc/3779060?query=data%20science',
'//doc/3495410?query=data%20science',
'//doc/4308832?query=data%20science',
'//doc/4079881?query=data%20science'
]

links = list(map(lambda s: 'https://www.kommersant.ru' + s, docs))
print(links)

['https://www.kommersant.ru//doc/5041434?query=data%20science', 'https://www.kommersant.ru//doc/5041567?query=data%20science', 'https://www.kommersant.ru//doc/4283670?query=data%20science', 'https://www.kommersant.ru//doc/3712659?query=data%20science', 'https://www.kommersant.ru//doc/4997267?query=data%20science', 'https://www.kommersant.ru//doc/4372673?query=data%20science', 'https://www.kommersant.ru//doc/3779060?query=data%20science', 'https://www.kommersant.ru//doc/3495410?query=data%20science', 'https://www.kommersant.ru//doc/4308832?query=data%20science', 'https://www.kommersant.ru//doc/4079881?query=data%20science']


In [ ]:
data = [(0.00632, 6.575, 65.2, 296.0, 4.98),
(0.02731, 6.421, 78.9, 242.0, 9.14),
(0.02729, 7.185, 61.1, 242.0, 4.03),
(0.03237, 6.998, 45.8, 222.0, 2.94),
(0.06905, 7.147, 54.2, 222.0, 5.33),
(0.02985, 6.43, 58.7, 222.0, 5.21),
(0.08829, 6.012, 66.6, 311.0, 12.43)]

updated_data = list(map(lambda x: (*x, round(x[0]*x[3]*x[4], 2)), data))
print(updated_data)

[(0.00632, 6.575, 65.2, 296.0, 4.98, 9.32), (0.02731, 6.421, 78.9, 242.0, 9.14, 60.41), (0.02729, 7.185, 61.1, 242.0, 4.03, 26.61), (0.03237, 6.998, 45.8, 222.0, 2.94, 21.13), (0.06905, 7.147, 54.2, 222.0, 5.33, 81.7), (0.02985, 6.43, 58.7, 222.0, 5.21, 34.53), (0.08829, 6.012, 66.6, 311.0, 12.43, 341.31)]


In [ ]:
prices = [34562, 66572, 25683, 17683, 56389, 28973]

filtered_prices = list(filter(lambda x: x<= 30000, prices))
print(filtered_prices)
## filtered_prices = [25683, 17683, 28973]

[25683, 17683, 28973]


In [ ]:
family_list = [
    'certificate of a large family',
    'social card',
    'maternity capital',
    'parking permit',
    'tax benefit',
    'reimbursement of expenses',
    "compensation for the purchase of children's goods"
 ]

def filter_family(lst):
    res = list(filter(lambda x: x in family_list, lst))
    return res


print(filter_family(['newborn registration', 'parking permit',
                     'maternity capital', 'tax benefit', 'medical policy']))
## ['parking permit', 'maternity capital', 'tax benefit']
print(filter_family(['reimbursement of expenses', 'parking permit', 'maternity capital', 'medical policy']))
## ['reimbursement of expenses', 'parking permit', 'maternity capital']


['parking permit', 'maternity capital', 'tax benefit']
['reimbursement of expenses', 'parking permit', 'maternity capital']


In [ ]:
reg = [('Ivanov', 'Sergej', 24, 9, 1995),
      ('Smith', 'John', 13, 2, 2003),
      ('Petrova', 'Maria', 13, 3, 2003)]

new_reg = list(filter(lambda x: (x[4] > 2000), reg))
new_reg = list(map(lambda x: (x[0]+' '+x[1][0]+'.', *x[-3:]), new_reg))
print(new_reg)
#new_reg = [('Smith J.', 13, 2, 2003), ('Petrova M.', 13, 3, 2003)]

[('Smith J.', 13, 2, 2003), ('Petrova M.', 13, 3, 2003)]


In [ ]:
data = [(0.00632, 6.575, 65.2, 296.0, 4.98),
 (0.02731, 6.421, 78.9, 242.0, 9.14),
 (0.02729, 7.185, 61.1, 242.0, 4.03),
 (0.03237, 6.998, 45.8, 222.0, 2.94),
 (0.06905, 7.147, 54.2, 222.0, 5.33),
 (0.02985, 6.43, 58.7, 222.0, 5.21),
 (0.08829, 6.012, 66.6, 311.0, 12.43)]

filtered_data = list(map(lambda x: (*x, round(x[0]*x[3]*x[4], 2)), data))
filtered_data = list(filter(lambda x: (x[-1] > 60), filtered_data))
print(filtered_data)

[(0.02731, 6.421, 78.9, 242.0, 9.14, 60.41), (0.06905, 7.147, 54.2, 222.0, 5.33, 81.7), (0.08829, 6.012, 66.6, 311.0, 12.43, 341.31)]


In [ ]:
3**(2)

9

# Модуль ООП

In [ ]:
class DepartmentReport():

    def __init__(self, company_name):
        """
        Метод инициализации класса.
        Создаёт атрибуты revenues и company
        """
        #ваш код здесь
        self.revenues = []
        self.company = company_name

    def add_revenue(self, amount):
        """
        Метод для добавления выручки отдела в список revenues.
        Если атрибута revenues ещё не существует, метод должен создавать пустой список перед добавлением выручки.
        """
        #ваш код здесь
        self.revenues.append(amount)

    def average_revenue(self):
        """
        Вычисляет average_revenue — среднюю выручку по отделам — округляя до целого.
        Метод возвращает строку в формате:
        'Average department revenue for <company>: <average_revenue>'
        """
        #ваш код здесь
        return (f"Average department revenue for {self.company}: {round(sum(self.revenues) / len(self.revenues))}")

report = DepartmentReport(company_name="Danon")
print(report.company)
# Danon

report.add_revenue(1_000_000)
report.add_revenue(400_000)

print(report.average_revenue())
# Average department revenue for Danon: 700000


Danon
Average department revenue for Danon: 700000


In [ ]:
# отслеживание состояний
class Client():
    # Базовые данные
    def __init__(self, email, order_num, registration_year):
        self.email = email
        self.order_num = order_num
        self.registration_year = registration_year
        self.discount = 0

    # Оформление заказа
    def make_order(self, price):
        self.update_discount()
        self.order_num += 1
        # Здесь было бы оформление заказа, но мы просто выведем его цену
        discounted_price = price * (1 - self.discount)
        print(f"Order price for {self.email} is {discounted_price}")

    # Назначение скидки
    def update_discount(self):
        if self.registration_year < 2018 and self.order_num >= 5:
            self.discount = 0.1


# Применение

# Сделаем подобие базы
client_db = [
    Client("max@gmail.com", 2, 2019),
    Client("lova@yandex.ru", 10, 2015),
    Client("german@sberbank.ru", 4, 2017)
]


# Сгенерируем заказы
client_db[0].make_order(100)
# => Order price for max@gmail.com is 100

client_db[1].make_order(200)
# => Order price for lova@yandex.ru is 180.0

client_db[2].make_order(500)
# => Order price for german@sberbank.ru is 500

client_db[2].make_order(500)
# => Order price for german@sberbank.ru is 450.0

Order price for max@gmail.com is 100
Order price for lova@yandex.ru is 180.0
Order price for german@sberbank.ru is 500
Order price for german@sberbank.ru is 450.0


In [ ]:
class User():
    # базовые данные
    def __init__(self, email, password, balance):
        self.email = email
        self.password = password
        self.balance = balance

    # метод реализует проверку почты и пароля
    def login(self, email, password):
        if self.email == email and self.password == password:
            return True
        else:
            return False
    # метод должен принимать в качестве аргумента некоторое число и изменять текущий баланс счёта на величину amount
    def update_balance(self, amount):
        self.balance += amount

user = User("gosha@roskino.org", "qwerty", 20_000)
print(user.login("gosha@roskino.org", "qwerty123"))
# False
print(user.login("gosha@roskino.org", "qwerty"))
# True
user.update_balance(200)
user.update_balance(-500)
print(user.balance)
# 19700


False
True
19700


Классы могут пригодиться, если вы регулярно делаете над данными одну и ту же последовательность разноплановых функций. Вы можете упаковать их в класс и в дальнейшем сразу получать результат по загруженным данным.

In [ ]:
# комбинация операций
import statistics

class DataFrame():
    def __init__(self, column, fill_value=0):
        # Инициализируем атрибуты
        self.column = column
        self.fill_value = fill_value
        # Заполним пропуски
        self.fill_missed()
        # Конвертируем все элементы в числа
        self.to_float()

    def fill_missed(self):
        for i, value in enumerate(self.column):
            if value is None or value == '':
                self.column[i] = self.fill_value

    def to_float(self):
        self.column = [float(value) for value in self.column]

    def median(self):
        return statistics.median(self.column)

    def mean(self):
        return statistics.mean(self.column)

    def deviation(self):
        return statistics.stdev(self.column)



# Воспользуемся классом
df = DataFrame(["1", 17, 4, None, 8])

print(df.column)
# => [1.0, 17.0, 4.0, 0.0, 8.0]
print(df.deviation())
# => 6.89
print(df.median())
# => 4.0

[1.0, 17.0, 4.0, 0.0, 8.0]
6.892024376045111
4.0


In [ ]:
class IntDataFrame():
    # преобразуем строковые элементы в целочисленные в момент создания объекта
    def __init__(self, column):
        self.column = [int(s) for s in column]
    # отбираем ненулевые элементы
    def count(self):
        return len([num for num in self.column if num != 0])
    # определяем количество уникальных элементов
    def unique(self):
        return len(set(self.column))

df = IntDataFrame([4.7, 4, 3, 0, 2.4, 0.3, 4])

print(df.column)
# [4, 4, 3, 0, 2, 0, 4]

print(df.count())
# 5

print(df.unique())
# 4


[4, 4, 3, 0, 2, 0, 4]
5
4


Классы можно использовать тогда, когда у вас есть процесс, который требует сложной конфигурации, повторяющейся из раза в раз. Можно написать класс-обёртку, который сведёт этот процесс к одному-двум методам.

In [ ]:
# класс - ОБЕРТКА
import pickle
from datetime import datetime
from os import path

class Dumper():
    def __init__(self, archive_dir="/content/archive/"):
        self.archive_dir = archive_dir

    def dump(self, data):
        # Библиотека pickle позволяет доставать и класть объекты в файл
        with open(self.get_file_name(), 'wb') as file:
            pickle.dump(data, file)

    def load_for_day(self, day):
        file_name = path.join(self.archive_dir, day + ".pkl")
        with open(file_name, 'rb') as file:
            sets = pickle.load(file)
        return sets

    # возвращает корректное имя для файла
    def get_file_name(self):
        today = datetime.now().strftime("%y-%m-%d")
        return path.join(self.archive_dir, today + ".pkl")


# Пример использования

data = {
    'perfomance': [10, 20, 10],
    'clients': {"Romashka": 10, "Vector": 34}
}


dumper = Dumper()

# Сохраним данные
dumper.dump(data)

# Восстановим для сегодняшней даты
file_name = datetime.now().strftime("%y-%m-%d")
restored_data = dumper.load_for_day(file_name)
print(restored_data)
# => {'perfomance': [10, 20, 10], 'clients': {'Romashka': 10, 'Vector': 34}}

In [ ]:
class OwnLogger():
    def __init__(self):
        # инициализируем словарь логов
        self.logs = {"info": None, "warning": None, "error": None, "all": None}

    def log(self, message, level):
        # если сообщений данного уровня нет
        if self.logs[level] == None:
            # создаем пустой список
            self.logs[level] = []

        # добавляем в список уровня сообщение
        self.logs[level].append(message)
        # длобавляем в список всех сообщений
        if self.logs['all'] == None:
            # создаем пустой список
            self.logs['all'] = []
        else:
            self.logs['all'].append(message)

    def show_last(self, level='all'):
        # если нет сообщений данного уровня
        if self.logs[level] == None:
            return None
        elif level in ('info', 'warning', 'error'):
            # выдаем последнее сообщение данного уровня
            return self.logs[level][-1]
        elif level == 'all':
            return self.logs['all'][-1]


logger = OwnLogger()
logger.log("System started", "info")
print(logger.show_last("error"))
# None
# Некоторые интерпретаторы Python могут не выводить None, тогда в этой проверке у вас будет пустая строка
logger.log("Connection instable", "warning")
logger.log("Connection lost", "error")

print(logger.show_last())
# Connection lost
print(logger.show_last("info"))
# System started

None
Connection lost
System started


Классы, как и библиотечные функции, можно импортировать в другие программы. Для этого нужно положить класс в отдельный файл в корне проекта и использовать ключевое слово import.

In [ ]:
# from <имя папки>.<имя файла> import <имя класса>

In [ ]:
import os

def walk_desc(path=None):
    start_path = path if path is not None else os.getcwd()

    for root, dirs, files in os.walk(start_path):
        print("Текущая директория", root)
        print("---")

        if dirs:
            print("Список папок", dirs)
        else:
            print("Папок нет")
        print("---")

        if files:
            print("Список файлов", files)
        else:
            print("Файлов нет")
        print("---")

        if files and dirs:
            print("Все пути:")
        for f in files:
            print("Файл ", os.path.join(root, f))
        for d in dirs:
            print("Папка ", os.path.join(root, d))
        print("===")

walk_desc()

Текущая директория /content
---
Список папок ['.config', 'sample_data']
---
Файлов нет
---
Папка  /content/.config
Папка  /content/sample_data
===
Текущая директория /content/.config
---
Список папок ['logs', 'configurations']
---
Список файлов ['active_config', '.last_survey_prompt.yaml', '.last_opt_in_prompt.yaml', '.last_update_check.json', 'gce', 'config_sentinel', 'default_configs.db']
---
Все пути:
Файл  /content/.config/active_config
Файл  /content/.config/.last_survey_prompt.yaml
Файл  /content/.config/.last_opt_in_prompt.yaml
Файл  /content/.config/.last_update_check.json
Файл  /content/.config/gce
Файл  /content/.config/config_sentinel
Файл  /content/.config/default_configs.db
Папка  /content/.config/logs
Папка  /content/.config/configurations
===
Текущая директория /content/.config/logs
---
Список папок ['2023.10.06']
---
Файлов нет
---
Папка  /content/.config/logs/2023.10.06
===
Текущая директория /content/.config/logs/2023.10.06
---
Папок нет
---
Список файлов ['13.24.42.8

# Модуль 5

In [7]:
def check_duplicates(lst):
    for i in range(0, len(lst)):
        elem = lst.pop(0)
        print(lst)
        if elem in lst:
            return True
    return False

lst = [0, 0, 1, 2, 3, 4, 5, 5, 6, 7]
print(check_duplicates(lst))
# True

lst = list(range(0, 15))
print(check_duplicates(lst))
# False

[0, 1, 2, 3, 4, 5, 5, 6, 7]
True
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
[6, 7, 8, 9, 10, 11, 12, 13, 14]
[7, 8, 9, 10, 11, 12, 13, 14]
[8, 9, 10, 11, 12, 13, 14]
[9, 10, 11, 12, 13, 14]
[10, 11, 12, 13, 14]
[11, 12, 13, 14]
[12, 13, 14]
[13, 14]
[14]
[]
False


In [13]:
def swap_places(lst):
    first_elem = lst.pop(0)
    last_elem = lst.pop(-1)
    lst.insert(0, last_elem)
    lst.append(first_elem)
    return lst

print(swap_places([1, 2, 3]))
## [3, 2, 1]
print(swap_places([1, 2, 3, 4, 5]))
## [5, 2, 3, 4, 1]
print(swap_places(['н', 'л', 'о', 'с']))
## ['с', 'л', 'о', 'н']


[2]
[3, 2, 1]
[2, 3, 4]
[5, 2, 3, 4, 1]
['л', 'о']
['с', 'л', 'о', 'н']


In [38]:
'''
В нашем распоряжении есть список строк разной длины.
Напишите функцию equalize_lengths(), которая принимает на вход список и возвращает новый список из строк одинаковой длины.
Длина итоговой строки должна быть равна длине самой длинной из строк.
Если конкретная строка короче самой длинной, её необходимо дополнить до требуемого количества символов нижними подчёркиваниями
с правого края.
Важно! Результирующий список должен быть отсортирован от меньшего к большему
по количеству добавленных символов нижнего подчёркивания. То есть первым должен идти элемент с максимальной длиной строки.
'''
def equalize_lengths(lst):
    max_length = max([len(s) for s in lst])
    l1 = []
    l2 = []

    for s in lst:
        if len(s) == max_length:
            l1.append(s)
        elif len(s) > max_length:
            l1.append(s[:max_length])
        elif len(s) < max_length:
            l2.append(s + '_'*(max_length - len(s)))

    l2 = sorted(l2, key=lambda x: x.count('_'), reverse=False)
    l1.extend(l2)
    return l1

print(equalize_lengths(['крот', 'белка', 'выхухоль']))
# ['выхухоль', 'белка___', 'крот____']

print(equalize_lengths(['a', 'aa', 'aaa', 'aaaa', 'aaaaa']))
# ['aaaaa', 'aaaa_', 'aaa__', 'aa___', 'a____']

print(equalize_lengths(['qweasdqweas', 'q', 'rteww', 'ewqqqqq']))
# ['qweasdqweas', 'ewqqqqq____', 'rteww______', 'q__________']

['выхухоль', 'белка___', 'крот____']
['aaaaa', 'aaaa_', 'aaa__', 'aa___', 'a____']
['qweasdqweas', 'ewqqqqq____', 'rteww______', 'q__________']


In [39]:
from prompt_toolkit.shortcuts.prompt import E
def check_number_sign(number):
    if number > 0:
        return 1
    elif number < 0:
        return -1
    else:
        return 0



print(check_number_sign(5290))
# 1
print(check_number_sign(-983))
# - 1
print(check_number_sign(0))
# 0

1
-1
0


In [42]:
def lucky_ticket(ticket_number):
    sum1 = 0
    sum2 = 0
    for el in str(ticket_number)[:3]:
        sum1 += int(el)
    for el in str(ticket_number)[3:]:
        sum2 += int(el)
    if sum1 == sum2:
        return True
    else:
        return False

print(lucky_ticket(111111))
# True
print(lucky_ticket(123456))
# False

True
False


In [45]:
def matrix_sum(matrix1, matrix2):
    sum_matrix = []

    if len(matrix1) == len(matrix2):
        for i in range(len(matrix1)):
            if len(matrix1[i]) != len(matrix2[i]):
                print("Error! Matrices dimensions are different!")
                return None
            else:
                sum_matrix.append(list(map(lambda x, y: x + y, matrix1[i], matrix2[i])))
        return sum_matrix
    else:
        print("Error! Matrices dimensions are different!")
        return None


matrix_example = [
          [1, 5, 4],
          [4, 2, -2],
          [7, 65, 88]
]

print(matrix_sum(matrix1=matrix_example, matrix2=matrix_example))
# [[2, 10, 8], [8, 4, -4], [14, 130, 176]]

matrix1_example = [
          [1, 5, 4],
          [4, 2, -2]
]

matrix2_example = [
          [10, 15, 43],
          [41, 2, -2],
          [7, 5, 7]
]

print(matrix_sum(matrix1=matrix1_example, matrix2=matrix2_example))
# Error! Matrices dimensions are different!
# None

matrix1_example = [
          [1, 5, 4, 5],
          [4, 2, -2, -5],
          [4, 2, -2, -5]
]

matrix2_example = [
          [10, 15, 43],
          [41, 2, -2],
          [7, 5, 7]
]

print(matrix_sum(matrix1=matrix1_example, matrix2=matrix2_example))
#Error! Matrices dimensions are different!
#None

[[2, 10, 8], [8, 4, -4], [14, 130, 176]]
Error! Matrices dimensions are different!
None
Error! Matrices dimensions are different!
None


In [48]:
def print_personal_data(**kwargs):
    for key, value in sorted(kwargs.items()):
        print(f"{key}: {value}")


print_personal_data(first_name='John', last_name='Doe', age=28, position='Python developer')
# age: 28
# first_name: John
# last_name: Doe
# position: Python developer

print_personal_data(first_name='Jack', last_name='Smith', age=32, work_experience = '5 years', position='Project manager')
# age: 32
# first_name: Jack
# last_name: Smith
# position: Project manager
# work_experience: 5 years

age: 28
first_name: John
last_name: Doe
position: Python developer
age: 32
first_name: Jack
last_name: Smith
position: Project manager
work_experience: 5 years


In [50]:
def get_words_list(text):
    punctuation_list = ['.', ',', ';', ':', '...', '!', '?', '-', '"', '(', ')']
    text = text.lower()
    for el in text:
        if el in punctuation_list:
            text = text.replace(el, '')

    return text.split()

text_example = "Arrakis, the planet known as Dune, is forever his place."

print(get_words_list(text=text_example))
# ['arrakis', 'the', 'planet', 'known', 'as', 'dune', 'is', 'forever', 'his', 'place']

['arrakis', 'the', 'planet', 'known', 'as', 'dune', 'is', 'forever', 'his', 'place']


In [55]:
def get_unique_words(words_list):
    list_words = sorted(list(set(words_list)))
    return list_words

words_list_example = ['and', 'take', 'the', 'most', 'special', 'care', 'that', 'you', 'locate', "muad'dib", 'in', 'his', 'place', 'the', 'planet', 'arrakis', 'do', 'not', 'be', 'deceived', 'by', 'the', 'fact', 'that', 'he', 'was', 'born', 'on', 'caladan', 'and', 'lived', 'his', 'first', 'fifteen', 'years', 'there', 'arrakis', 'the', 'planet', 'known', 'as', 'dune', 'is', 'forever', 'his', 'place']

print(get_unique_words(words_list=words_list_example))
## ['and', 'arrakis', 'as', 'be', 'born', 'by', 'caladan', 'care', 'deceived', 'do', 'dune', 'fact', 'fifteen', 'first', 'forever', 'he', 'his', 'in', 'is', 'known', 'lived', 'locate', 'most', "muad'dib", 'not', 'on', 'place', 'planet', 'special', 'take', 'that', 'the', 'there', 'was', 'years', 'you']


['and', 'arrakis', 'as', 'be', 'born', 'by', 'caladan', 'care', 'deceived', 'do', 'dune', 'fact', 'fifteen', 'first', 'forever', 'he', 'his', 'in', 'is', 'known', 'lived', 'locate', 'most', "muad'dib", 'not', 'on', 'place', 'planet', 'special', 'take', 'that', 'the', 'there', 'was', 'years', 'you']


In [72]:
def get_most_frequent_word(text):
    def get_words_list(text):
        punctuation_list = ['.', ',', ';', ':', '...', '!', '?', '-', '"', '(', ')']
        clean_text = text.lower()
        for el in clean_text:
            if el in punctuation_list:
                clean_text = clean_text.replace(el, '')
        return clean_text
    def get_unique_words(words_list):
        unique_words = sorted(list(set(words_list)))
        return unique_words

    clean_text = get_words_list(text)
    #print(clean_text)
    unique_words = get_unique_words(clean_text.split())
    #print(unique_words)
    dict_words = {}
    for word in unique_words:
        dict_words[word] = clean_text.count(' ' + word + ' ')
    dict_words = {k: v for k, v in sorted(dict_words.items(), key=lambda item: item[1], reverse=True)}
    #print(dict_words)
    return list(dict_words.keys())[0]

text_example = "A beginning is the time for taking the most delicate care that the balances are correct. This every sister of the Bene Gesserit knows. To begin your study of the life of Muad'Dib, then take care that you first place him in his time: born in the 57th year of the Padishah Emperor, Shaddam IV. And take the most special care that you locate Muad'Dib in his place: the planet Arrakis. Do not be deceived by the fact that he was born on Caladan and lived his first fifteen years there. Arrakis, the planet known as Dune, is forever his place."
print(get_most_frequent_word(text_example))
# the

text_example = "Есть урок, который идет не сорок пять минут, а всю жизнь. Этот урок проходит и в классе, и в поле, и дома, и в лесу. Я назвал этот урок седьмым потому, что в школе обычно бывает не больше шести уроков. Не удивляйтесь, если я скажу, что учителем на этом уроке может быть и береза возле вашего дома, и бабушка, и вы сами (В. Песков)"
print(get_most_frequent_word(text_example))
# и


the
и


In [116]:
def get_total_score(data):
    data = list(map(list, data))
    #print(data)
    data_slice = list(map(lambda x: x[-3:], data))
    total_scores = list(map((lambda x: sum(x)), data_slice))
    #print(total_scores)
    data = list(map(lambda x, y: x + [y], data, total_scores))
    data = sorted(data, key=lambda data: data[-1])
    data = list(map(tuple, data))
    return data

data = [
    ('Amanda', 37, 78, 67),
    ('Patricia', 78, 93, 68),
    ('Marcos', 79, 67, 89),
    ('Dmitry', 67, 68, 100),
    ('Andrey', 100, 78, 76),
    ('Victoria', 93, 69, 96),
]

print(get_total_score(data))
# [('Amanda', 37, 78, 67, 182), ('Marcos', 79, 67, 89, 235), ('Dmitry', 67, 68, 100, 235), ('Patricia', 78, 93, 68, 239), ('Andrey', 100, 78, 76, 254), ('Victoria', 93, 69, 96, 258)]


[('Amanda', 37, 78, 67, 182), ('Marcos', 79, 67, 89, 235), ('Dmitry', 67, 68, 100, 235), ('Patricia', 78, 93, 68, 239), ('Andrey', 100, 78, 76, 254), ('Victoria', 93, 69, 96, 258)]


In [ ]:
data = {
    "type": "video",
    "videoID": "vid001",
    "links": [
        {"type":"video", "videoID":"vid002", "links":[]},
        {   "type":"video",
            "videoID":"vid003",
            "links": [
            {"type": "video", "videoID":"vid004"},
            {"type": "video", "videoID":"vid005"},
            ]
        },
        {"type":"video", "videoID":"vid006"},
        {   "type":"video",
            "videoID":"vid007",
            "links": [
            {"type":"video", "videoID":"vid008", "links": [
                {   "type":"video",
                    "videoID":"vid009",
                    "links": [{"type":"video", "videoID":"vid010"}]
                }
            ]}
        ]},
    ]
}

def find_video(data):
    # условие окончания рекурсии


    return

In [126]:
'''
Небольшая частная сыроварня, которая делает поставки в разные рестораны, просит вас проанализировать их производство с целью
его дальнейшего расширения.
Сыроварня предоставила данные о каждом из производимых ей сыров в виде словаря cheese_data.
Ключами словаря являются названия сыров, а значениями — списки, в которых последовательно указываются следующие параметры сыра:
закупочная цена (рублей за 100 грамм);
максимальный объём производства (килограммов в месяц);
жирность (в процентах);
тип (твёрдый, полутвёрдый, мягкий, полумягкий).
'''

cheese_data = {
    'чеддер': [370, 5000, 33, 'твердый'],
    'пармезан': [510, 4000, 29, 'твердый'],
    'гауда': [250, 3700, 27, 'полутвердый'],
    'эдам': [220, 10000, 30, 'полутвердый'],
    'горгонзола': [320, 3000, 32, 'полумягкий'],
    'рокфор': [340, 15000, 31, 'полумягкий'],
    'стилтон': [360, 7000, 35, 'полумягкий'],
    'камамбер': [250, 8000, 24, 'мягкий'],
    'бри': [310, 6500, 28, 'мягкий'],
}

def filter_by_fat(cheese_data, n):
    dict_cheese = {}
    for key, value in cheese_data.items():
        if value[-2] < n:
            dict_cheese[key] = value[-2]
    return dict_cheese

print(filter_by_fat(cheese_data, n=30))
# {'пармезан': 29, 'гауда': 27, 'камамбер': 24, 'бри': 28}

print(filter_by_fat(cheese_data, n=25))
# {'камамбер': 24}

def count_money(cheese_data):
    total_money = 0
    for value in cheese_data.values():
        total_money += value[0]*10*value[1]
    return total_money

print(count_money(cheese_data))
## 196100000

def find_cheese_type(cheese_data, cheese_type):
    list_cheese = []
    for key, value in cheese_data.items():
        if value[-1] == cheese_type:
            list_cheese.append(key)
    return list_cheese


find_cheese_type(cheese_data, cheese_type='полумягкий')
# ['горгонзола', 'рокфор', 'стилтон']

def sort_cheese(cheese_data):
    sorted_cheese = sorted(cheese_data.items(), key=lambda item: item[1][0])
    list_cheese = list(map(lambda x: x[0], sorted_cheese))
    return list_cheese

print(sort_cheese(cheese_data))
# ['эдам', 'гауда', 'камамбер', 'бри', 'горгонзола', 'рокфор', 'стилтон', 'чеддер', 'пармезан']

{'пармезан': 29, 'гауда': 27, 'камамбер': 24, 'бри': 28}
{'камамбер': 24}
196100000
['эдам', 'гауда', 'камамбер', 'бри', 'горгонзола', 'рокфор', 'стилтон', 'чеддер', 'пармезан']


In [129]:
def purchase(ingredients):
    unique_parts = list(set(ingredients))
    if len(unique_parts) == len(ingredients):
        print('Ваш заказ оформлен верно')
    else:
        for unique_part in unique_parts:
            count_part = ingredients.count(unique_part)
            if count_part > 1:
                print(f'Вы продублировали ингредиент {unique_part} в заказе {count_part} раз(а)')


ingredients = ['молоко коровье', 'молоко овечье', 'бактерии', 'молоко козье', 'сливки', 'фермент', 'закваска', 'молоко коровье', 'соль', 'молоко коровье', 'бактерии', 'молоко овечье', 'кислота лимонная', 'грибки', 'соль', 'дрожжи', 'кислота уксусная', 'кальций', 'калий', 'каротин', 'аннато', 'специя', 'пряность', 'ароматизатор', 'соль', 'кислота молочная']

print(purchase(ingredients))
# Вы продублировали ингредиент бактерии в заказе 2 раз(а)
# Вы продублировали ингредиент молоко коровье в заказе 3 раз(а)
# Вы продублировали ингредиент молоко овечье в заказе 2 раз(а)
# Вы продублировали ингредиент соль в заказе 3 раз(а)


Вы продублировали ингредиент молоко овечье в заказе 2 раз(а)
Вы продублировали ингредиент соль в заказе 3 раз(а)
Вы продублировали ингредиент молоко коровье в заказе 3 раз(а)
Вы продублировали ингредиент бактерии в заказе 2 раз(а)
None


# Модуль 6.2 (NumPy)

In [4]:
from collections import deque

temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]

# Посчитаем динамику средней температуры с усреднением за каждые последние 7 дней для каждого рассматриваемого дня. Для этого воспользуемся очередью с параметром maxlen=7:
days = deque(maxlen=7)
 
for temp in temps:
    # Добавляем температуру в очередь
    days.append(temp)
    # Если длина очереди оказалась равной максимальной длине очереди (7),
    # печатаем среднюю температуру за последние 7 дней
    if len(days) == days.maxlen:
        print(round(sum(days) / len(days), 2), end='; ')
# Напечатаем пустую строку, чтобы завершить действие параметра
# end. Иначе следующая строка окажется напечатанной на предыдущей
print("")
# Результат:
# 20.77; 21.27; 22.16; 23.3; 24.44; 24.94; 25.56; 26.2; 25.97;
# 25.94; 25.57; 25.1; 24.81; 24.21; 23.23; 22.57; 21.41; 20.4;
# 19.6; 19.1; 19.04; 18.96; 19.44; 20.01; 20.67;

20.77; 21.27; 22.16; 23.3; 24.44; 24.94; 25.56; 26.2; 25.97; 25.94; 25.57; 25.1; 24.81; 24.21; 23.23; 22.57; 21.41; 20.4; 19.6; 19.1; 19.04; 18.96; 19.44; 20.01; 20.67; 


In [1]:
'''
Напишите функцию brackets(line), которая определяет, является ли последовательность из круглых скобок line правильной.
Примечание 1. Какая последовательность скобок правильная?
Правильной скобочной последовательностью назовём такую последовательность скобок, в которой для каждой открывающей скобки есть последующая соответствующая ей закрывающая скобка.
Соответственно, остальные скобочные последовательности назовём неправильными. Пустую строку будем считать правильной последовательностью.
Примечание 2.Для решения этой задачи потребуется использовать стек.
Посимвольно переберите строку. Если встретилась открывающаяся скобка, положите её в стек. Если встретилась закрывающаяся скобка, извлеките скобку из стека.
Если стек пустой, то есть извлечь скобку нельзя, последовательность неправильная.
Если строка закончилась и стек стал пустым, последовательность правильная.
Если в стеке остались скобки, последовательность неправильная.
'''

from collections import deque

def brackets(line):
    dq = deque()
    for el in line:
        if el == '(':
           dq.append(el)           
        elif el == ')' and dq.count('(') > 0:
            dq.pop()
        elif el == ')' and dq.count('(') == 0:
            return False
    if dq.count('(') == 0:
        return True
    else:  
        return False
    
print(brackets("(()())"))
# True
print(brackets(""))
# True
print(brackets("(()()))"))
# False


True
True
False


In [13]:
from collections import Counter

center = [['Milk', 'Bread'], ['Meat']]
south = [['Milk'], ['Bread'], ['Meat']]
north = [['Milk', 'Bread'], ['Meat'], 'Bread']

def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

lst_center = flatten(center)
lst_south = flatten(south)
lst_north = flatten(north)

dict_market = {'center':len(lst_center), 'south':len(lst_south), 'north':len(lst_north)}
# в каком магазине было куплено больше всего товаров
print(max(dict_market, key=dict_market.get))
# Сколько раз покупали самый редкий товар в магазине north
center_counter = Counter(lst_center)
south_counter = Counter(lst_south)
north_counter = Counter(lst_north)
print(north_counter.most_common()[-1][1])
# Выберите товар, который в магазине center покупали чаще, чем в магазине north
#center_counter.subtract(north_counter)
#print(center_counter)
# Есть ли такой товар, который в одном из магазинов покупали чаще, чем в двух других вместе взятых? Если да, выберите магазин с настолько популярным товаром
#center_counter.subtract(south_counter + north_counter)
#print(center_counter)
#south_counter.subtract(center_counter + north_counter)
#print(south_counter)
#north_counter.subtract(center_counter + south_counter)
#print(south_counter)
center_counter + south_counter + north_counter

north
1


Counter({'Bread': 4, 'Milk': 3, 'Meat': 3})

In [45]:
'''
Дан список кортежей ratings с рейтингами кафе. Кортеж состоит из названия и рейтинга кафе.
Необходимо отсортировать кортеж по убыванию рейтинга. Если рейтинги совпадают, то отсортировать кафе дополнительно по названию в алфавитном порядке.
Получите словарь cafes с упорядоченными ключами из отсортированного списка, где ключи — названия кафе, а значения — их рейтинг.
'''
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]

from collections import OrderedDict

dict_cafes = OrderedDict(sorted(dict(ratings).items(), key=lambda x: x[1], reverse=True))

print(dict_cafes)

OrderedDict([('WokToWork', 4.9), ('WokAndRice', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('Nice Cakes', 3.9), ('Old York', 3.3), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3)])


In [43]:
'''
Напишите функцию task_manager(tasks), которая принимает список задач tasks для нескольких серверов. Каждый элемент списка состоит из кортежа (<номер задачи>, <название сервера>, <высокий приоритет задачи>).
Функция должна создавать словарь и заполнять его задачами по следующему принципу: название сервера — ключ, по которому хранится очередь задач для конкретного сервера.
Если поступает задача без высокого приоритета (последний элемент кортежа — False), добавить номер задачи в конец очереди. Если приоритет высокий, добавить номер в начало.
Для словаря используйте defaultdict, для очереди — deque.
Функция возвращает полученный словарь с задачами.
'''
from collections import defaultdict, deque

tasks = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]


def task_manager(tasks):
    
    d = defaultdict(deque)    
    
    for task, name_server, priority in tasks:
        if priority == False:            
            d[name_server].append(task)
            #d.setdefault(name_server, deque()).append(task)
        else:
            d[name_server].appendleft(task)            
            #d.setdefault(name_server, deque()).appendleft(task)                
        
    return d


print(task_manager(tasks))
# defaultdict(, {'voltage': deque([41667, 35364]),
# 'office': deque([36871, 40690, 33850])})


defaultdict(<class 'collections.deque'>, {'office': deque([36871, 40690, 33850]), 'voltage': deque([41667, 35364])})


In [48]:
import numpy as np

print(np.iinfo(np.int8))
print(np.iinfo(np.int16))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [49]:
np.iinfo(np.uint64)

iinfo(min=0, max=18446744073709551615, dtype=uint64)

In [50]:
np.finfo(np.float64)

finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)

In [51]:
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

<class 'numpy.bool_'>
<class 'numpy.bytes_'>
<class 'numpy.clongdouble'>
<class 'numpy.complex128'>
<class 'numpy.complex64'>
<class 'numpy.datetime64'>
<class 'numpy.float16'>
<class 'numpy.float32'>
<class 'numpy.float64'>
<class 'numpy.int16'>
<class 'numpy.int32'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.intc'>
<class 'numpy.longdouble'>
<class 'numpy.object_'>
<class 'numpy.str_'>
<class 'numpy.timedelta64'>
<class 'numpy.uint16'>
<class 'numpy.uint32'>
<class 'numpy.uint64'>
<class 'numpy.uint8'>
<class 'numpy.uintc'>
<class 'numpy.void'>


In [55]:
np.finfo(np.float16)

finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)

In [57]:
arr, step = np.linspace(-6, 21, 60, endpoint=True, retstep=True)
print(round(step, 2))
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(step, 2))

0.46
0.45


In [66]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

elem_5_3 = mystery[4,2]
print(elem_5_3)
last = mystery[-1,-1]
print(last)
line_4 = mystery[3, :]
print(line_4)
col_2 = mystery[:, -2]
print(col_2)
part = mystery[1:4, 2:5]
print(part)
rev = mystery[:, -1][::-1]
print(rev)
trans = mystery.transpose()
print(trans)

30305
-32037
[13240  7994 32592 20149 13754 11795  -564]
[-17182  15790  25397  11795  12578    -47]
[[-1297 -4593  6451]
 [28655 -6012 21762]
 [32592 20149 13754]]
[-32037  29943   -564   8225   7181 -18049]
[[-13586  25936  13348  13240 -21725 -16841]
 [ 15203 -30968  28049   7994  -8681 -25392]
 [ 28445  -1297  28655  32592  30305 -17278]
 [-27117  -4593  -6012  20149  22260  11740]
 [ -1781   6451  21762  13754 -17918   5916]
 [-17182  15790  25397  11795  12578    -47]
 [-18049   7181   8225   -564  29943 -32037]]


In [87]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)
print(mystery)

nans_index = np.isnan(mystery)
print('Массив bool', nans_index)

n_nan = mystery[np.isnan(mystery)].size
print('Количество пропусков', n_nan)

mystery_new = mystery.copy()
mystery_new[np.isnan(mystery_new)] = 0
print('Новый массив с нулями', mystery_new)


mystery_int = mystery_new.astype('int32')
print('Новый массив с целыми значениями', mystery_int)
print(mystery)
array = np.sort(mystery)
print('Сортировка массива', array)

table = array.reshape(5,3, order='F')
print(table)
col = table[:, 1]
print(col)

[ 12279. -26024.  28745.     nan  31244.  -2365.  -6974.  -9212.     nan
 -17722.  16132.  25933.     nan -16431.  29810.]
Массив bool [False False False  True False False False False  True False False False
  True False False]
Количество пропусков 3
Новый массив с нулями [ 12279. -26024.  28745.      0.  31244.  -2365.  -6974.  -9212.      0.
 -17722.  16132.  25933.      0. -16431.  29810.]
Новый массив с целыми значениями [ 12279 -26024  28745      0  31244  -2365  -6974  -9212      0 -17722
  16132  25933      0 -16431  29810]
[ 12279. -26024.  28745.     nan  31244.  -2365.  -6974.  -9212.     nan
 -17722.  16132.  25933.     nan -16431.  29810.]
Сортировка массива [-26024. -17722. -16431.  -9212.  -6974.  -2365.  12279.  16132.  25933.
  28745.  29810.  31244.     nan     nan     nan]
[[-26024.  -2365.  29810.]
 [-17722.  12279.  31244.]
 [-16431.  16132.     nan]
 [ -9212.  25933.     nan]
 [ -6974.  28745.     nan]]
[-2365. 12279. 16132. 25933. 28745.]


In [92]:
a = np.array([23, 34, 27])
b = np.array([-54,   1,  46])
c = np.array([46, 68, 54])

import numpy as np

len_a = np.linalg.norm(a)
len_b = np.linalg.norm(b)
len_c = np.linalg.norm(c)
# Найдите сонаправленные векторы
print(len_a + len_b == np.linalg.norm(a + b))
print(len_a + len_c == np.linalg.norm(a + c))
print(len_b + len_c == np.linalg.norm(b + c))
# Найдите пару векторов, расстояние между которыми больше 100
print(np.linalg.norm(a - b))
print(np.linalg.norm(a - c))
print(np.linalg.norm(b - c))
# Найдите перпендикулярные векторы
print(np.dot(a, b))
print(np.dot(a, c))
print(np.dot(b, c))

False
True
False
85.901105930017
49.13247398615299
120.6358155772986
34
4828
68


In [98]:
mystery2 = np.array([481,  18, 308,  13, 652, 391,  63,  62, 353, 111, 805, 251,  36, 544, 600, 799, 283, 880,
 470, 599, 814, 507, 242, 650, 180, 860, 979, 298, 621, 197, 572, 976, 905, 427, 119, 905,
  64, 430, 742, 563, 382, 211, 228, 760, 567, 366, 103, 409, 211, 952,   5, 493, 151, 267,
 517, 495, 375,  80, 341,  39, 560,  85, 490,  44,  17, 151,  42, 688, 648, 501, 437, 154,
  66,  28, 921, 642, 196, 719, 208, 492, 538, 687, 841, 933, 386, 719, 114, 261, 838, 228,
 120, 508, 316, 476, 233, 902, 698, 471, 604, 172, 993, 790, 557, 129, 446,  64, 317, 997,
 509, 710, 909, 147, 228, 595, 188, 246, 728, 509, 365, 139, 773, 426, 929, 888, 534, 513,
 666,  77, 299, 943, 985, 588, 137,  31, 385, 405, 980, 854, 327, 714, 318, 909, 803, 334,
 130, 949, 532, 640, 820, 975, 889, 240, 878, 294, 899, 488, 639, 961, 819, 649, 939, 163,
 209, 879, 479, 573, 557,  25, 783, 332, 311, 425, 140, 678, 766, 492, 234, 316, 811, 447,
 772, 325, 640, 387, 858, 208, 739, 870, 227, 385,  24, 286,  22, 599, 951, 994, 457,  99,
 238, 172, 549, 932, 412, 545, 713,  19, 785, 931, 684, 333, 630, 752, 191, 949, 200, 361,
 887, 243, 753, 600, 635, 243, 173, 249, 294, 583, 106, 772, 848, 387, 874, 321, 562,  96,
 211, 561, 918, 868, 206, 745, 710, 869, 387, 600, 726, 179, 33])

print(mystery2.min())
print(mystery2.mean())
print(np.median(mystery2))
print(round(mystery2.std(), 2))

5
487.7692307692308
490.0
291.18


In [99]:
np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [1]:
import numpy as np

np.random.seed(2021)
simple = np.random.rand()
print(simple)
randoms = np.random.uniform(-150, 2021, size=120)
print(randoms)
table = np.random.randint(1, 100, size=(3, 2))
print(table)
arr = np.arange(2, 17)
even = arr[arr % 2 == 0]
print(even)
mix = np.random.permutation(even)
print(mix)
select = np.random.choice(even, size=3, replace=False)
print(select)
triplet = np.random.permutation(select)
print(triplet)

0.6059782788074047
[ 1.44214488e+03  1.51654277e+02  5.28813265e+02  2.01501516e+03
  1.28240517e+02  2.38594033e+02  1.48460111e+03  1.28755048e+03
  1.55273730e+03  6.03577336e+01 -2.28417401e+01  1.93936169e+03
  1.18854621e+03  3.80736459e+01  1.06852230e+03  1.18847514e+03
  1.94250320e+03  1.09681462e+03  6.55790201e+02  8.31607324e+02
  2.88216888e+02  1.08596141e+03  2.73553360e+02  1.11722142e+03
  8.84076551e+02  9.74175063e+02  1.63694713e+03  1.43966053e+03
 -7.88273550e-02  1.30919192e+03  1.24700551e+03  1.64761920e+03
  2.93903055e+02  1.19056852e+03  1.19102890e+03  5.03619976e+02
  1.74254881e+03  1.13013901e+03  1.98142287e+03  8.10086179e+02
  1.24235695e+02  9.54671885e+02  7.87407805e+02  1.83850479e+03
  1.38927296e+03  1.78361285e+03  1.12847065e+03  1.23255777e+03
  5.92935602e+02  1.63845066e+03  5.12482326e+02  5.17676863e+02
  2.87071500e+02  4.25673103e+02  1.26315547e+03  1.85668749e+02
  6.93866612e+02  1.25597031e+03  1.69165738e+03 -1.14109610e+01
  7.49

In [44]:
'''
Напишите функцию get_chess, которая принимает на вход длину стороны квадрата a и возвращает двумерный массив формы (a, a),
заполненный 0 и 1 в шахматном порядке. В левом верхнем углу всегда должен быть ноль.
Примечание. воспользуйтесь функцией np.zeros, а затем с помощью срезов без циклов задайте необходимым элементам значение 1.
В Python для получения каждого второго элемента используется срез [::2]. Подумайте, как грамотно применить этот принцип к двумерному массиву.
'''
import numpy as np

def get_chess(a) -> int:
    if a == 1:
        matrix_zeros = np.zeros((a, a))
        return matrix_zeros
    elif a > 1:
        matrix_zeros = np.zeros((a, a))
        matrix_flatten = matrix_zeros.flatten()
        matrix_flatten[1::2] = 1
        matrix_chess = matrix_flatten.reshape((a, a))
        matrix_chess[1::2] = np.flip(matrix_chess[1::2], axis=1) 
        return matrix_chess

get_chess(8)

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [3]:
'''
Вы разрабатываете приложение для прослушивания музыки. Конечно же, там будет доступна функция перемешивания плейлиста.
Пользователю может настолько понравиться перемешанная версия плейлиста, что он захочет сохранить его копию. Однако вы не хотите хранить в памяти новую версию плейлиста,
а просто хотите сохранять тот seed, с которым он был сгенерирован.
Для этого напишите функцию shuffle_seed(array), которая принимает на вход массив из чисел,
генерирует случайное число для seed в диапазоне от 0 до 2**32 - 1 (включительно) и возвращает кортеж:
перемешанный с данным seed массив (исходный массив должен оставаться без изменений), а также seed, с которым этот массив был получен.
'''
import numpy as np

def shuffle_seed(arr):
    num_seed = round(np.random.uniform(0, 2**32 - 1, 1)[0])
    arr_shuffle = np.random.permutation(arr)
    return (arr_shuffle, num_seed)

array = [1, 2, 3, 4, 5]
shuffle_seed(array)
# (array([1, 3, 2, 4, 5]), 2332342819)
shuffle_seed(array)
# (array([4, 5, 2, 3, 1]), 4155165971)


(array([4, 1, 3, 2, 5]), 3617028139)

In [37]:
'''
Напишите функцию min_max_dist, которая принимает на вход неограниченное число векторов через запятую.
Гарантируется, что все векторы, которые передаются, одинаковой длины.
Функция возвращает минимальное и максимальное расстояние между векторами в виде кортежа.
'''

import numpy as np
from numpy.linalg import norm

def min_max_dist(*vectors):
    
    matrix_vec = np.array(vectors)
    norm_list = norm(matrix_vec, axis=1, ord=2)
    #print(norm_list)
    distance_list = [abs(i-j) for i, j in zip(norm_list[:-1], norm_list[1:])]
    distance_list.append(abs(norm_list[-1] - norm_list[0]))
    #print(distance_list)
    return (min(distance_list), max(distance_list))


vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
 
print(min_max_dist(vec1, vec2, vec3))
# (5.196152422706632, 10.392304845413264)

vec1 = np.array([100, 200, 300])
vec2 = np.array([400, 500, 600])

print(min_max_dist(vec1, vec2))
# (519.6152422706632, 519.6152422706632)

(5.033307000618182, 10.186730890410178)
(503.33070006181805, 503.33070006181805)


In [41]:
''' 
Напишите функцию any_normal, которая принимает на вход неограниченное число векторов через запятую.
Гарантируется, что все векторы, которые передаются, одинаковой длины.
Функция возвращает True, если есть хотя бы одна пара перпендикулярных векторов. Иначе возвращает False.
'''
import numpy as np


def any_normal(*vectors):
    matrix_vec = np.array(vectors)
    for i in range(1, len(matrix_vec)):
        if np.dot(matrix_vec[i], matrix_vec[i-1]) == 0:
            return True
        else:
            return False

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
print(any_normal(vec1, vec2, vec3))
# True

True


In [50]:
''' 
Напишите функцию get_loto(num), генерирующую трёхмерный массив случайных целых чисел от 1 до 100 (включительно).
Это поля для игры в лото.
Трёхмерный массив должен состоять из таблиц чисел формы 5х5, то есть итоговая форма — (num, 5, 5).
Функция возвращает полученный массив.
'''
import numpy as np

def get_loto(num):
    arr_3d = np.zeros((num, 5, 5))
    for i in range(num):
        for j in  range(5):
            for z in range(5):
                arr_3d[i][j][z] = np.random.randint(1, 100)
    return arr_3d

print(get_loto(3))


[[[96.  5. 52. 50. 26.]
  [11. 69. 57. 38. 95.]
  [33. 61. 62. 15. 35.]
  [50. 19.  6. 83. 81.]
  [67. 12. 92. 18.  6.]]

 [[36. 44. 70. 82. 13.]
  [23.  4. 98. 22. 31.]
  [72. 62. 92.  4. 25.]
  [51. 86. 63. 84. 77.]
  [94. 82. 36. 89. 21.]]

 [[76. 34. 62. 92. 66.]
  [62.  3. 39.  1. 89.]
  [50. 21. 38. 33. 97.]
  [62. 55. 80. 71. 85.]
  [ 9. 84. 72. 68. 90.]]]


In [83]:
'''
Напишите функцию get_unique_loto(num).
Она так же, как и функция в задании 10.10, генерирует num полей для игры в лото,
однако теперь на каждом поле 5х5 числа не могут повторяться.
Функция также должна возвращать массив формы num x 5 x 5.
'''
import numpy as np

def get_unique_loto(num):
    arr_3d = np.zeros((num, 5, 5))
    for i in range(num):
        arr_3d[i] = np.random.choice(np.random.uniform(1,100, size=100), (5,5), replace=False)
    return arr_3d

#print(get_unique_loto(3))
#print(np.shape(get_unique_loto(3)))
a = get_unique_loto(5)

check = []
for i in a:
  check.append(len(set(i.flatten())))
  
print(check)

[25, 25, 25, 25, 25]
